version: '2'
services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:17-alpine
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: shopping
      POSTGRES_USER: johndoe
    ports:
      - 5432:5432
